---
- name: Display Windows Hostname
  debug:
    var: ansible_hostname

- name: Display Operating System
  debug:
    var: ansible_distribution

- name: Display IP Address
  debug:
    var: ansible_ip_addresses
