---
- name: Display Hostname
  debug:
    msg: "{{ hostname_message }}: {{ ansible_hostname }}"

- name: Display Operating System
  debug:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: Display IP Address
  debug:
    msg: "{{ ansible_default_ipv4.address }}"

- name: Display Current Date and Time
  debug:
    msg: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

- name: Create Windows Info Marker File
  ansible.windows.win_copy:
    content: "Windows information role executed successfully."
    dest: C:\Temp\windows_info_status.txt
  notify: Restart Windows Spooler

- name: Copy Welcome Template
  ansible.builtin.template:
    src: welcome.j2
    dest: C:\Temp\Welcome.txt

- name: Copy Role README
  ansible.windows.win_copy:
    src: README.md
    dest: C:\Temp\Role_README.md

- name: Create Logs Folder
  ansible.windows.win_file:
    path: C:\Training\Logs
    state: directory

- name: Create Report File
  ansible.windows.win_copy:
    content: "Ansible Windows Information Collection Completed Successfully."
    dest: C:\Training\Logs\report.txt

- name: Display Completion Message
  debug:
    msg: "Windows information collection completed successfully."
