---
- name: Display Hostname
  debug:
    msg: "{{ hostname_message }}: {{ ansible_hostname }}"

- name: Display Operating System
  debug:
    msg: "{{ os_message }}: {{ ansible_distribution }}"

- name: Display IP Address
  debug:
    msg: "{{ ip_message }}: {{ ansible_ip_addresses }}"
