---
- name: Create Local Windows User
  hosts: windows
  gather_facts: yes

  tasks:

    - name: Create Local User
      ansible.windows.win_user:
        name: demo_user
        password: "P@ssw0rd123!"
        state: present
        groups:
          - Users

    - name: Display Result
      debug:
        msg: "Local User Created Successfully."
