---
- name: Restart Windows Services
  hosts: windows
  gather_facts: yes

  tasks:

    - name: Restart Print Spooler Service
      ansible.windows.win_service:
        name: Spooler
        state: restarted

    - name: Display Restart Status
      debug:
        msg: "Print Spooler Service Restarted Successfully."
